// Generated from the Agricon product catalog.
export const catalogProductImages: Record<string, string> = {
  "layer-cage": "/catalog/products/layer-cage.jpg",
  "broiler-cage": "/catalog/products/broiler-cage.jpg",
  "chick-cage": "/catalog/products/chick-cage.jpg",
  "automatic-cage": "/catalog/products/automatic-cage.jpg",
  "hatcher-equipment": "/catalog/products/hatcher-equipment.jpg",
  "floor-rearing-equipment": "/catalog/products/floor-rearing-equipment.jpg",
  "cage-accessories": "/catalog/products/cage-accessories.jpg",
  "breeding-accessories": "/catalog/products/breeding-accessories.jpg",
  "farm-fence": "/catalog/products/farm-fence.jpg",
  "cattle-panels": "/catalog/products/cattle-panels.jpg",
  "livestock-scale": "/catalog/products/livestock-scale.jpg",
  "farrow-pen": "/catalog/products/farrow-pen.jpg",
  "goat-pen": "/catalog/products/goat-pen.jpg",
  "rabbit-cage": "/catalog/products/rabbit-cage.jpg",
  "livestock-accessories": "/catalog/products/livestock-accessories.jpg",
  "water-pump": "/catalog/products/water-pump.jpg",
  "aerator": "/catalog/products/aerator.jpg",
  "fish-pond": "/catalog/products/fish-pond.jpg",
  "floating-cage": "/catalog/products/floating-cage.jpg",
  "fish-net": "/catalog/products/fish-net.jpg",
  "aquaculture-accessories": "/catalog/products/aquaculture-accessories.jpg",
  "pellet-machine": "/catalog/products/pellet-machine.jpg",
  "extruder-machine": "/catalog/products/extruder-machine.jpg",
  "grinding-machine": "/catalog/products/grinding-machine.jpg",
  "grass-chaff-machine": "/catalog/products/grass-chaff-machine.jpg",
  "mixing-machine": "/catalog/products/mixing-machine.jpg",
  "drying-machine": "/catalog/products/drying-machine.jpg",
  "rice-mill-machine": "/catalog/products/rice-mill-machine.jpg",
  "production-line": "/catalog/products/production-line.jpg",
  "metal-structure": "/catalog/products/metal-structure.jpg",
  "greenhouse": "/catalog/products/greenhouse.jpg",
  "exhaust-fan": "/catalog/products/exhaust-fan.jpg",
  "cooling-pad": "/catalog/products/cooling-pad.jpg",
  "slatted-floor": "/catalog/products/slatted-floor.jpg",
  "manure-scraper": "/catalog/products/manure-scraper.jpg",
  "feed-silo": "/catalog/products/feed-silo.jpg",
  "environment-controller": "/catalog/products/environment-controller.jpg",
  "disinfection-equipment": "/catalog/products/disinfection-equipment.jpg",
  "plucker-machine": "/catalog/products/plucker-machine.jpg",
  "scalding-machine": "/catalog/products/scalding-machine.jpg",
  "bleeding-cone": "/catalog/products/bleeding-cone.jpg",
  "cutting-machine": "/catalog/products/cutting-machine.jpg",
  "working-table": "/catalog/products/working-table.jpg",
  "automatic-processing-machine": "/catalog/products/automatic-processing-machine.jpg",
  "planter": "/catalog/products/planter.jpg",
  "weed-cutter": "/catalog/products/weed-cutter.jpg",
  "sprayer": "/catalog/products/sprayer.jpg",
  "mist-maker": "/catalog/products/mist-maker.jpg",
  "irrigation-equipment": "/catalog/products/irrigation-equipment.jpg",
  "packing-bag": "/catalog/products/packing-bag.jpg",
  "tractor": "/catalog/products/tractor.jpg",
  "harvester": "/catalog/products/harvester.jpg",
  "tricycle": "/catalog/products/tricycle.jpg",
  "walking-tractor": "/catalog/products/walking-tractor.jpg",
  "welded-wire-mesh": "/catalog/products/welded-wire-mesh.jpg",
  "cattle-fence": "/catalog/products/cattle-fence.jpg",
  "chain-link-fence": "/catalog/products/chain-link-fence.jpg",
  "hexagonal-wire-mesh": "/catalog/products/hexagonal-wire-mesh.jpg",
  "cage-mesh": "/catalog/products/cage-mesh.jpg",
  "egg-tray-machine": "/catalog/products/egg-tray-machine.jpg",
  "egg-sizing-machine": "/catalog/products/egg-sizing-machine.jpg",
  "egg-conveyor-machine": "/catalog/products/egg-conveyor-machine.jpg",
  "egg-counting-machine": "/catalog/products/egg-counting-machine.jpg",
  "brick-making-machine": "/catalog/products/brick-making-machine.jpg"
}

// Full image galleries per product (from the AGRICON catalog — 4-5 photos per product)
export const catalogProductGallery: Record<string, string[]> = {
  "aerator": ["/catalog/products/aerator.jpg", "/catalog/products/aerator-2.jpg", "/catalog/products/aerator-3.jpg", "/catalog/products/aerator-4.jpg"],
  "aquaculture-accessories": ["/catalog/products/aquaculture-accessories.jpg", "/catalog/products/aquaculture-accessories-2.jpg", "/catalog/products/aquaculture-accessories-3.jpg", "/catalog/products/aquaculture-accessories-4.jpg"],
  "automatic-cage": ["/catalog/products/automatic-cage.jpg", "/catalog/products/automatic-cage-2.jpg", "/catalog/products/automatic-cage-3.jpg", "/catalog/products/automatic-cage-4.jpg", "/catalog/products/automatic-cage-5.jpg"],
  "automatic-processing-machine": ["/catalog/products/automatic-processing-machine.jpg", "/catalog/products/automatic-processing-machine-2.jpg", "/catalog/products/automatic-processing-machine-3.jpg", "/catalog/products/automatic-processing-machine-4.jpg"],
  "bleeding-cone": ["/catalog/products/bleeding-cone.jpg", "/catalog/products/bleeding-cone-2.jpg", "/catalog/products/bleeding-cone-3.jpg", "/catalog/products/bleeding-cone-4.jpg"],
  "breeding-accessories": ["/catalog/products/breeding-accessories.jpg", "/catalog/products/breeding-accessories-2.jpg", "/catalog/products/breeding-accessories-3.jpg", "/catalog/products/breeding-accessories-4.jpg", "/catalog/products/breeding-accessories-5.jpg"],
  "brick-making-machine": ["/catalog/products/brick-making-machine.jpg", "/catalog/products/brick-making-machine-2.jpg", "/catalog/products/brick-making-machine-3.jpg", "/catalog/products/brick-making-machine-4.jpg"],
  "broiler-cage": ["/catalog/products/broiler-cage.jpg", "/catalog/products/broiler-cage-2.jpg", "/catalog/products/broiler-cage-3.jpg", "/catalog/products/broiler-cage-4.jpg", "/catalog/products/broiler-cage-5.jpg"],
  "cage-accessories": ["/catalog/products/cage-accessories.jpg", "/catalog/products/cage-accessories-2.jpg", "/catalog/products/cage-accessories-3.jpg", "/catalog/products/cage-accessories-4.jpg", "/catalog/products/cage-accessories-5.jpg"],
  "cage-mesh": ["/catalog/products/cage-mesh.jpg", "/catalog/products/cage-mesh-2.jpg", "/catalog/products/cage-mesh-3.jpg", "/catalog/products/cage-mesh-4.jpg"],
  "cattle-fence": ["/catalog/products/cattle-fence.jpg", "/catalog/products/cattle-fence-2.jpg", "/catalog/products/cattle-fence-3.jpg", "/catalog/products/cattle-fence-4.jpg", "/catalog/products/cattle-fence-5.jpg"],
  "cattle-panels": ["/catalog/products/cattle-panels.jpg", "/catalog/products/cattle-panels-2.jpg", "/catalog/products/cattle-panels-3.jpg", "/catalog/products/cattle-panels-4.jpg", "/catalog/products/cattle-panels-5.jpg"],
  "chain-link-fence": ["/catalog/products/chain-link-fence.jpg", "/catalog/products/chain-link-fence-2.jpg", "/catalog/products/chain-link-fence-3.jpg", "/catalog/products/chain-link-fence-4.jpg"],
  "chick-cage": ["/catalog/products/chick-cage.jpg", "/catalog/products/chick-cage-2.jpg", "/catalog/products/chick-cage-3.jpg", "/catalog/products/chick-cage-4.jpg", "/catalog/products/chick-cage-5.jpg"],
  "cooling-pad": ["/catalog/products/cooling-pad.jpg", "/catalog/products/cooling-pad-2.jpg", "/catalog/products/cooling-pad-3.jpg", "/catalog/products/cooling-pad-4.jpg", "/catalog/products/cooling-pad-5.jpg"],
  "cutting-machine": ["/catalog/products/cutting-machine.jpg", "/catalog/products/cutting-machine-2.jpg", "/catalog/products/cutting-machine-3.jpg", "/catalog/products/cutting-machine-4.jpg"],
  "disinfection-equipment": ["/catalog/products/disinfection-equipment.jpg", "/catalog/products/disinfection-equipment-2.jpg", "/catalog/products/disinfection-equipment-3.jpg", "/catalog/products/disinfection-equipment-4.jpg"],
  "drying-machine": ["/catalog/products/drying-machine.jpg", "/catalog/products/drying-machine-2.jpg", "/catalog/products/drying-machine-3.jpg", "/catalog/products/drying-machine-4.jpg", "/catalog/products/drying-machine-5.jpg"],
  "egg-conveyor-machine": ["/catalog/products/egg-conveyor-machine.jpg", "/catalog/products/egg-conveyor-machine-2.jpg", "/catalog/products/egg-conveyor-machine-3.jpg", "/catalog/products/egg-conveyor-machine-4.jpg"],
  "egg-counting-machine": ["/catalog/products/egg-counting-machine.jpg", "/catalog/products/egg-counting-machine-2.jpg", "/catalog/products/egg-counting-machine-3.jpg", "/catalog/products/egg-counting-machine-4.jpg"],
  "egg-sizing-machine": ["/catalog/products/egg-sizing-machine.jpg", "/catalog/products/egg-sizing-machine-2.jpg", "/catalog/products/egg-sizing-machine-3.jpg", "/catalog/products/egg-sizing-machine-4.jpg", "/catalog/products/egg-sizing-machine-5.jpg"],
  "egg-tray-machine": ["/catalog/products/egg-tray-machine.jpg", "/catalog/products/egg-tray-machine-2.jpg", "/catalog/products/egg-tray-machine-3.jpg", "/catalog/products/egg-tray-machine-4.jpg", "/catalog/products/egg-tray-machine-5.jpg"],
  "environment-controller": ["/catalog/products/environment-controller.jpg", "/catalog/products/environment-controller-2.jpg", "/catalog/products/environment-controller-3.jpg", "/catalog/products/environment-controller-4.jpg"],
  "exhaust-fan": ["/catalog/products/exhaust-fan.jpg", "/catalog/products/exhaust-fan-2.jpg", "/catalog/products/exhaust-fan-3.jpg", "/catalog/products/exhaust-fan-4.jpg", "/catalog/products/exhaust-fan-5.jpg"],
  "extruder-machine": ["/catalog/products/extruder-machine.jpg", "/catalog/products/extruder-machine-2.jpg", "/catalog/products/extruder-machine-3.jpg", "/catalog/products/extruder-machine-4.jpg", "/catalog/products/extruder-machine-5.jpg"],
  "farm-fence": ["/catalog/products/farm-fence.jpg", "/catalog/products/farm-fence-2.jpg", "/catalog/products/farm-fence-3.jpg", "/catalog/products/farm-fence-4.jpg", "/catalog/products/farm-fence-5.jpg"],
  "farrow-pen": ["/catalog/products/farrow-pen.jpg", "/catalog/products/farrow-pen-2.jpg", "/catalog/products/farrow-pen-3.jpg", "/catalog/products/farrow-pen-4.jpg", "/catalog/products/farrow-pen-5.jpg"],
  "feed-silo": ["/catalog/products/feed-silo.jpg", "/catalog/products/feed-silo-2.jpg", "/catalog/products/feed-silo-3.jpg", "/catalog/products/feed-silo-4.jpg"],
  "fish-net": ["/catalog/products/fish-net.jpg", "/catalog/products/fish-net-2.jpg", "/catalog/products/fish-net-3.jpg", "/catalog/products/fish-net-4.jpg"],
  "fish-pond": ["/catalog/products/fish-pond.jpg", "/catalog/products/fish-pond-2.jpg", "/catalog/products/fish-pond-3.jpg", "/catalog/products/fish-pond-4.jpg"],
  "floating-cage": ["/catalog/products/floating-cage.jpg", "/catalog/products/floating-cage-2.jpg", "/catalog/products/floating-cage-3.jpg", "/catalog/products/floating-cage-4.jpg"],
  "floor-rearing-equipment": ["/catalog/products/floor-rearing-equipment.jpg", "/catalog/products/floor-rearing-equipment-2.jpg", "/catalog/products/floor-rearing-equipment-3.jpg", "/catalog/products/floor-rearing-equipment-4.jpg", "/catalog/products/floor-rearing-equipment-5.jpg"],
  "goat-pen": ["/catalog/products/goat-pen.jpg", "/catalog/products/goat-pen-2.jpg", "/catalog/products/goat-pen-3.jpg", "/catalog/products/goat-pen-4.jpg", "/catalog/products/goat-pen-5.jpg"],
  "grass-chaff-machine": ["/catalog/products/grass-chaff-machine.jpg", "/catalog/products/grass-chaff-machine-2.jpg", "/catalog/products/grass-chaff-machine-3.jpg", "/catalog/products/grass-chaff-machine-4.jpg", "/catalog/products/grass-chaff-machine-5.jpg"],
  "greenhouse": ["/catalog/products/greenhouse.jpg", "/catalog/products/greenhouse-2.jpg", "/catalog/products/greenhouse-3.jpg", "/catalog/products/greenhouse-4.jpg", "/catalog/products/greenhouse-5.jpg"],
  "grinding-machine": ["/catalog/products/grinding-machine.jpg", "/catalog/products/grinding-machine-2.jpg", "/catalog/products/grinding-machine-3.jpg", "/catalog/products/grinding-machine-4.jpg", "/catalog/products/grinding-machine-5.jpg"],
  "harvester": ["/catalog/products/harvester.jpg", "/catalog/products/harvester-2.jpg", "/catalog/products/harvester-3.jpg", "/catalog/products/harvester-4.jpg", "/catalog/products/harvester-5.jpg"],
  "hatcher-equipment": ["/catalog/products/hatcher-equipment.jpg", "/catalog/products/hatcher-equipment-2.jpg", "/catalog/products/hatcher-equipment-3.jpg", "/catalog/products/hatcher-equipment-4.jpg", "/catalog/products/hatcher-equipment-5.jpg"],
  "hexagonal-wire-mesh": ["/catalog/products/hexagonal-wire-mesh.jpg", "/catalog/products/hexagonal-wire-mesh-2.jpg", "/catalog/products/hexagonal-wire-mesh-3.jpg", "/catalog/products/hexagonal-wire-mesh-4.jpg"],
  "irrigation-equipment": ["/catalog/products/irrigation-equipment.jpg", "/catalog/products/irrigation-equipment-2.jpg", "/catalog/products/irrigation-equipment-3.jpg", "/catalog/products/irrigation-equipment-4.jpg"],
  "layer-cage": ["/catalog/products/layer-cage.jpg", "/catalog/products/layer-cage-2.jpg", "/catalog/products/layer-cage-3.jpg", "/catalog/products/layer-cage-4.jpg", "/catalog/products/layer-cage-5.jpg"],
  "livestock-accessories": ["/catalog/products/livestock-accessories.jpg", "/catalog/products/livestock-accessories-2.jpg", "/catalog/products/livestock-accessories-3.jpg", "/catalog/products/livestock-accessories-4.jpg", "/catalog/products/livestock-accessories-5.jpg"],
  "livestock-scale": ["/catalog/products/livestock-scale.jpg", "/catalog/products/livestock-scale-2.jpg", "/catalog/products/livestock-scale-3.jpg", "/catalog/products/livestock-scale-4.jpg", "/catalog/products/livestock-scale-5.jpg"],
  "manure-scraper": ["/catalog/products/manure-scraper.jpg", "/catalog/products/manure-scraper-2.jpg", "/catalog/products/manure-scraper-3.jpg", "/catalog/products/manure-scraper-4.jpg"],
  "metal-structure": ["/catalog/products/metal-structure.jpg", "/catalog/products/metal-structure-2.jpg", "/catalog/products/metal-structure-3.jpg", "/catalog/products/metal-structure-4.jpg", "/catalog/products/metal-structure-5.jpg"],
  "mist-maker": ["/catalog/products/mist-maker.jpg", "/catalog/products/mist-maker-2.jpg", "/catalog/products/mist-maker-3.jpg", "/catalog/products/mist-maker-4.jpg"],
  "mixing-machine": ["/catalog/products/mixing-machine.jpg", "/catalog/products/mixing-machine-2.jpg", "/catalog/products/mixing-machine-3.jpg", "/catalog/products/mixing-machine-4.jpg"],
  "packing-bag": ["/catalog/products/packing-bag.jpg", "/catalog/products/packing-bag-2.jpg", "/catalog/products/packing-bag-3.jpg", "/catalog/products/packing-bag-4.jpg"],
  "pellet-machine": ["/catalog/products/pellet-machine.jpg", "/catalog/products/pellet-machine-2.jpg", "/catalog/products/pellet-machine-3.jpg", "/catalog/products/pellet-machine-4.jpg", "/catalog/products/pellet-machine-5.jpg"],
  "planter": ["/catalog/products/planter.jpg", "/catalog/products/planter-2.jpg", "/catalog/products/planter-3.jpg", "/catalog/products/planter-4.jpg"],
  "plucker-machine": ["/catalog/products/plucker-machine.jpg", "/catalog/products/plucker-machine-2.jpg", "/catalog/products/plucker-machine-3.jpg", "/catalog/products/plucker-machine-4.jpg"],
  "production-line": ["/catalog/products/production-line.jpg", "/catalog/products/production-line-2.jpg", "/catalog/products/production-line-3.jpg", "/catalog/products/production-line-4.jpg", "/catalog/products/production-line-5.jpg"],
  "rabbit-cage": ["/catalog/products/rabbit-cage.jpg", "/catalog/products/rabbit-cage-2.jpg", "/catalog/products/rabbit-cage-3.jpg", "/catalog/products/rabbit-cage-4.jpg"],
  "rice-mill-machine": ["/catalog/products/rice-mill-machine.jpg", "/catalog/products/rice-mill-machine-2.jpg", "/catalog/products/rice-mill-machine-3.jpg", "/catalog/products/rice-mill-machine-4.jpg", "/catalog/products/rice-mill-machine-5.jpg"],
  "scalding-machine": ["/catalog/products/scalding-machine.jpg", "/catalog/products/scalding-machine-2.jpg", "/catalog/products/scalding-machine-3.jpg", "/catalog/products/scalding-machine-4.jpg"],
  "slatted-floor": ["/catalog/products/slatted-floor.jpg", "/catalog/products/slatted-floor-2.jpg", "/catalog/products/slatted-floor-3.jpg", "/catalog/products/slatted-floor-4.jpg", "/catalog/products/slatted-floor-5.jpg"],
  "sprayer": ["/catalog/products/sprayer.jpg", "/catalog/products/sprayer-2.jpg", "/catalog/products/sprayer-3.jpg", "/catalog/products/sprayer-4.jpg"],
  "tractor": ["/catalog/products/tractor.jpg", "/catalog/products/tractor-2.jpg", "/catalog/products/tractor-3.jpg", "/catalog/products/tractor-4.jpg", "/catalog/products/tractor-5.jpg"],
  "tricycle": ["/catalog/products/tricycle.jpg", "/catalog/products/tricycle-2.jpg", "/catalog/products/tricycle-3.jpg", "/catalog/products/tricycle-4.jpg", "/catalog/products/tricycle-5.jpg"],
  "walking-tractor": ["/catalog/products/walking-tractor.jpg", "/catalog/products/walking-tractor-2.jpg", "/catalog/products/walking-tractor-3.jpg", "/catalog/products/walking-tractor-4.jpg", "/catalog/products/walking-tractor-5.jpg"],
  "water-pump": ["/catalog/products/water-pump.jpg", "/catalog/products/water-pump-2.jpg", "/catalog/products/water-pump-3.jpg", "/catalog/products/water-pump-4.jpg"],
  "weed-cutter": ["/catalog/products/weed-cutter.jpg", "/catalog/products/weed-cutter-2.jpg", "/catalog/products/weed-cutter-3.jpg", "/catalog/products/weed-cutter-4.jpg"],
  "welded-wire-mesh": ["/catalog/products/welded-wire-mesh.jpg", "/catalog/products/welded-wire-mesh-2.jpg", "/catalog/products/welded-wire-mesh-3.jpg", "/catalog/products/welded-wire-mesh-4.jpg", "/catalog/products/welded-wire-mesh-5.jpg"],
  "working-table": ["/catalog/products/working-table.jpg", "/catalog/products/working-table-2.jpg", "/catalog/products/working-table-3.jpg", "/catalog/products/working-table-4.jpg"]
}
