// Images selected from the company product catalog. Unsplash remains the final fallback
// for content that has not yet received a CMS or catalog image.

export const categoryImages: Record<string, string> = {
  "poultry-equipment": "/catalog/categories/poultry-equipment.jpg",
  "livestock-equipment": "/catalog/categories/livestock-equipment.jpg",
  "aquaculture-equipment": "/catalog/categories/aquaculture-equipment.jpg",
  "agriculture-machinery": "/catalog/categories/agriculture-machinery.jpg",
  "breeding-house-equipment": "/catalog/categories/breeding-house-equipment.jpg",
  "slaughter-equipment": "/catalog/categories/slaughter-equipment.jpg",
  "farming-tools": "/catalog/categories/farming-tools.jpg",
  "farming-vehicles": "/catalog/categories/farming-vehicles.jpg",
  "wire-mesh-fencing": "/catalog/categories/wire-mesh-fencing.jpg",
  "other-machines": "/catalog/categories/other-machines.jpg",
}

export const subcategoryImages: Record<string, string> = {
  "layer-cage": "/catalog/products/layer-cage.jpg",
  "broiler-cage": "/catalog/products/broiler-cage.jpg",
  "chick-cage": "/catalog/products/chick-cage.jpg",
  "automatic-cage": "/catalog/products/automatic-cage.jpg",
  "hatcher-equipment": "/catalog/products/hatcher-equipment.jpg",
  "floor-rearing-equipment": "/catalog/products/floor-rearing-equipment.jpg",
  "cage-accessories": "/catalog/products/cage-accessories.jpg",
  "breeding-accessories": "/catalog/products/breeding-accessories.jpg",
  "farm-fence": "/catalog/products/farm-fence.jpg",
  "cattle-panels": "/catalog/products/cattle-panels.jpg",
  "livestock-scale": "/catalog/products/livestock-scale.jpg",
  "farrow-pen": "/catalog/products/farrow-pen.jpg",
  "goat-pen": "/catalog/products/goat-pen.jpg",
  "rabbit-cage": "/catalog/products/rabbit-cage.jpg",
  "livestock-accessories": "/catalog/products/livestock-accessories.jpg",
  "water-pump": "/catalog/products/water-pump.jpg",
  "aerator": "/catalog/products/aerator.jpg",
  "fish-pond": "/catalog/products/fish-pond.jpg",
  "floating-cage": "/catalog/products/floating-cage.jpg",
  "fish-net": "/catalog/products/fish-net.jpg",
  "aquaculture-accessories": "/catalog/products/aquaculture-accessories.jpg",
  "pellet-machine": "/catalog/products/pellet-machine.jpg",
  "extruder-machine": "/catalog/products/extruder-machine.jpg",
  "grinding-machine": "/catalog/products/grinding-machine.jpg",
  "grass-chaff-machine": "/catalog/products/grass-chaff-machine.jpg",
  "mixing-machine": "/catalog/products/mixing-machine.jpg",
  "drying-machine": "/catalog/products/drying-machine.jpg",
  "rice-mill-machine": "/catalog/products/rice-mill-machine.jpg",
  "production-line": "/catalog/products/production-line.jpg",
  "metal-structure": "/catalog/products/metal-structure.jpg",
  "greenhouse": "/catalog/products/greenhouse.jpg",
  "exhaust-fan": "/catalog/products/exhaust-fan.jpg",
  "cooling-pad": "/catalog/products/cooling-pad.jpg",
  "slatted-floor": "/catalog/products/slatted-floor.jpg",
  "manure-scraper": "/catalog/products/manure-scraper.jpg",
  "feed-silo": "/catalog/products/feed-silo.jpg",
  "environment-controller": "/catalog/products/environment-controller.jpg",
  "disinfection-equipment": "/catalog/products/disinfection-equipment.jpg",
  "plucker-machine": "/catalog/products/plucker-machine.jpg",
  "scalding-machine": "/catalog/products/scalding-machine.jpg",
  "bleeding-cone": "/catalog/products/bleeding-cone.jpg",
  "cutting-machine": "/catalog/products/cutting-machine.jpg",
  "working-table": "/catalog/products/working-table.jpg",
  "automatic-processing-machine": "/catalog/products/automatic-processing-machine.jpg",
  "planter": "/catalog/products/planter.jpg",
  "weed-cutter": "/catalog/products/weed-cutter.jpg",
  "sprayer": "/catalog/products/sprayer.jpg",
  "mist-maker": "/catalog/products/mist-maker.jpg",
  "irrigation-equipment": "/catalog/products/irrigation-equipment.jpg",
  "packing-bag": "/catalog/products/packing-bag.jpg",
  "tractor": "/catalog/products/tractor.jpg",
  "harvester": "/catalog/products/harvester.jpg",
  "tricycle": "/catalog/products/tricycle.jpg",
  "walking-tractor": "/catalog/products/walking-tractor.jpg",
  "welded-wire-mesh": "/catalog/products/welded-wire-mesh.jpg",
  "cattle-fence": "/catalog/products/cattle-fence.jpg",
  "chain-link-fence": "/catalog/products/chain-link-fence.jpg",
  "hexagonal-wire-mesh": "/catalog/products/hexagonal-wire-mesh.jpg",
  "cage-mesh": "/catalog/products/cage-mesh.jpg",
  "egg-tray-machine": "/catalog/products/egg-tray-machine.jpg",
  "egg-sizing-machine": "/catalog/products/egg-sizing-machine.jpg",
  "egg-conveyor-machine": "/catalog/products/egg-conveyor-machine.jpg",
  "egg-counting-machine": "/catalog/products/egg-counting-machine.jpg",
  "brick-making-machine": "/catalog/products/brick-making-machine.jpg",
  "gestation-crate": "/catalog/products/gestation-crate.jpg",
  "transport-crate": "/catalog/products/transport-crate.png",
  "quail-cage": "/catalog/products/quail-cage.jpg",
  "screw-conveyor": "/catalog/products/screw-conveyor.png",
  "peanut-sheller": "/catalog/products/peanut-sheller.jpg",
  "threshing-machine": "/catalog/products/threshing-machine.jpg"
}

export const caseStudyImages: Record<string, string> = {
  "kenya-layer-farm": "/catalog/cases/kenya-layer-farm.jpg",
  "tanzania-layer-farm": "/catalog/cases/tanzania-layer-farm.jpg",
  "indonesia-goat-pen": "/catalog/cases/indonesia-goat-pen.jpg",
  "africa-cattle-fence": "/catalog/cases/africa-cattle-fence.jpg",
  "ghana-feed-mill": "/catalog/cases/ghana-feed-mill.jpg",
  "nigeria-feed-production": "/catalog/cases/nigeria-feed-production.jpg",
  "ecuador-greenhouse": "/catalog/cases/ecuador-greenhouse.jpg",
  "tanzania-ventilation": "/catalog/cases/tanzania-ventilation.jpg",
  "philippines-fish-cage": "/catalog/cases/philippines-fish-cage.jpg",
  "fish-farm-equipment": "/catalog/cases/fish-farm-equipment.jpg",
  "se-asia-farm-machines": "/catalog/cases/se-asia-farm-machines.jpg",
  "sa-crop-farming": "/catalog/cases/sa-crop-farming.jpg",
}

export const heroFallback = "/images/heroes/farm-landscape.jpg"

export function getImageUrl(slug: string, type: 'category' | 'subcategory' | 'case-study' = 'category'): string {
  const map = type === 'category' ? categoryImages : type === 'subcategory' ? subcategoryImages : caseStudyImages
  return map[slug] || heroFallback
}

// Full image galleries per case study (from the AGRICON catalog)
export const caseStudyGalleries: Record<string, string[]> = {
  "africa-cattle-fence": ["/catalog/cases/africa-cattle-fence.jpg", "/catalog/cases/africa-cattle-fence-2.jpg", "/catalog/cases/africa-cattle-fence-3.jpg", "/catalog/cases/africa-cattle-fence-4.jpg"],
  "ecuador-greenhouse": ["/catalog/cases/ecuador-greenhouse.jpg", "/catalog/cases/ecuador-greenhouse-2.jpg", "/catalog/cases/ecuador-greenhouse-3.jpg", "/catalog/cases/ecuador-greenhouse-4.jpg"],
  "ghana-feed-mill": ["/catalog/cases/ghana-feed-mill.jpg", "/catalog/cases/ghana-feed-mill-2.jpg", "/catalog/cases/ghana-feed-mill-3.jpg", "/catalog/cases/ghana-feed-mill-4.jpg"],
  "indonesia-goat-pen": ["/catalog/cases/indonesia-goat-pen.jpg", "/catalog/cases/indonesia-goat-pen-2.jpg", "/catalog/cases/indonesia-goat-pen-3.jpg", "/catalog/cases/indonesia-goat-pen-4.jpg"],
  "kenya-layer-farm": ["/catalog/cases/kenya-layer-farm.jpg", "/catalog/cases/kenya-layer-farm-2.jpg", "/catalog/cases/kenya-layer-farm-3.jpg", "/catalog/cases/kenya-layer-farm-4.jpg"],
  "nigeria-feed-production": ["/catalog/cases/nigeria-feed-production.jpg", "/catalog/cases/nigeria-feed-production-2.jpg", "/catalog/cases/nigeria-feed-production-3.jpg", "/catalog/cases/nigeria-feed-production-4.jpg"],
  "philippines-fish-cage": ["/catalog/cases/philippines-fish-cage.jpg", "/catalog/cases/philippines-fish-cage-2.jpg", "/catalog/cases/philippines-fish-cage-3.jpg", "/catalog/cases/philippines-fish-cage-4.jpg"],
  "fish-farm-equipment": ["/catalog/cases/fish-farm-equipment.jpg", "/catalog/cases/fish-farm-equipment-2.jpg", "/catalog/cases/fish-farm-equipment-3.jpg", "/catalog/cases/fish-farm-equipment-4.jpg"],
  "sa-crop-farming": ["/catalog/cases/sa-crop-farming.jpg", "/catalog/cases/sa-crop-farming-2.jpg", "/catalog/cases/sa-crop-farming-3.jpg", "/catalog/cases/sa-crop-farming-4.jpg"],
  "se-asia-farm-machines": ["/catalog/cases/se-asia-farm-machines.jpg", "/catalog/cases/se-asia-farm-machines-2.jpg", "/catalog/cases/se-asia-farm-machines-3.jpg", "/catalog/cases/se-asia-farm-machines-4.jpg"],
  "tanzania-layer-farm": ["/catalog/cases/tanzania-layer-farm.jpg", "/catalog/cases/tanzania-layer-farm-2.jpg", "/catalog/cases/tanzania-layer-farm-3.jpg", "/catalog/cases/tanzania-layer-farm-4.jpg"],
  "tanzania-ventilation": ["/catalog/cases/tanzania-ventilation.jpg", "/catalog/cases/tanzania-ventilation-2.jpg", "/catalog/cases/tanzania-ventilation-3.jpg", "/catalog/cases/tanzania-ventilation-4.jpg"]
}
