import type { Metadata } from 'next'
import { defaultLocale, getTranslations, locales, type Locale } from '@/i18n/config'

/** 站点规范域名（与 sitemap.ts 保持一致） */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://www.agricon.cn').replace(/\/$/, '')

/**
 * Default social-share card, used whenever a page/product has no CMS image of
 * its own. Generated by `scripts/generate-og-image.mjs` (1200×630, ~130 KB) —
 * keep it small: several platforms refuse oversized `og:image` files, and the
 * 4–8 MB source photos in `public/images` are far past those limits.
 */
export const DEFAULT_OG_IMAGE = '/images/og-default.jpg'

/**
 * Open Graph `og:locale` values.
 *
 * The OG spec is `language_TERRITORY` — language lowercase, territory uppercase
 * (e.g. `ru_RU`). Building these as `` `${locale}_${locale.toUpperCase()}` ``
 * produced the invalid `RU_RU` for every non-English locale, so social platforms
 * ignored the locale hint and often served the wrong-language preview. Swahili
 * and Arabic also need a concrete territory; there is no `sw_SW` / `ar_AR`.
 *
 * Single source of truth: the locale layout and `pageMetadata()` both read it.
 */
export const OG_LOCALES: Record<string, string> = {
  en: 'en_US',
  ru: 'ru_RU',
  fr: 'fr_FR',
  es: 'es_ES',
  sw: 'sw_KE',
  ar: 'ar_SA',
}

export const ogLocale = (locale: string): string => OG_LOCALES[locale] || OG_LOCALES.en

/**
 * 生成当前页面的 hreflang 与 canonical。
 * path 为相对 locale 的路径，如 ''（首页）或 '/about'。
 */
export function localizedAlternates(locale: Locale, path: string): Metadata['alternates'] {
  const rel = path === '' ? '' : path.startsWith('/') ? path : `/${path}`
  return {
    canonical: `/${locale}${rel}`,
    languages: {
      ...Object.fromEntries(locales.map((l) => [`${l}`, `/${l}${rel}`])),
      // x-default 告诉搜索引擎：没有语言匹配时该给哪一版（这里用默认语言 en）。
      // 多语言站的最佳实践，此前缺失。
      'x-default': `/${defaultLocale}${rel}`,
    } as Record<string, string>,
  }
}

/**
 * 页面级 metadata。
 *
 * **每个页面都必须调用它**：`[locale]/layout.tsx` 只提供兜底 title/description，
 * 页面若不覆盖就会原样继承 —— 这正是之前 14 个页面 `<title>` 完全相同的根因
 * （搜索引擎无法区分这些页面）。
 *
 * 文案来源优先级（都是"取到就用，取不到往下退"）：
 *   1. `t.meta.title` / `t.meta.description` —— 当 SEO 文案与页面可见标题不同时用
 *      （例如 /blog：可见 hero 是 "Blog"，而 meta description 更长）
 *   2. `t.hero.title` / `t.hero.description` —— 页面文案即 SEO 文案时用
 *   3. 调用方传入的英文兜底 `title` / `description`
 *
 * `key` 用于一个命名空间装多个页面的情况（`pages.json` → `about` /
 * `caseStudies` / `products` / `solutions`）。
 */
export function pageMetadata(
  locale: Locale,
  {
    path,
    namespace,
    key,
    title,
    description,
  }: { path: string; namespace?: string; key?: string; title: string; description: string },
): Metadata {
  let meta: { title?: string; description?: string } = {}
  let hero: { title?: string; description?: string } = {}
  if (namespace) {
    const table = getTranslations(locale, namespace) as Record<
      string,
      { meta?: typeof meta; hero?: typeof hero } | undefined
    >
    const source = (key ? table[key] : table) as { meta?: typeof meta; hero?: typeof hero } | undefined
    meta = source?.meta ?? {}
    hero = source?.hero ?? {}
  }
  const resolvedTitle = meta.title || hero.title || title
  const resolvedDescription = meta.description || hero.description || description
  return {
    title: resolvedTitle,
    description: resolvedDescription,
    alternates: localizedAlternates(locale, path),
    // All the layout-level social fields are restated here on purpose. Next
    // replaces the `openGraph`/`twitter` objects wholesale when a page defines
    // them, so a page that only set a title would otherwise drop `og:type`,
    // `og:site_name` and `og:locale` from its own tags.
    openGraph: {
      type: 'website',
      siteName: 'Agricon',
      locale: ogLocale(locale),
      title: resolvedTitle,
      description: resolvedDescription,
      images: [{ url: DEFAULT_OG_IMAGE, width: 1200, height: 630, alt: 'Agricon' }],
    },
    twitter: {
      card: 'summary_large_image',
      title: resolvedTitle,
      description: resolvedDescription,
      images: [DEFAULT_OG_IMAGE],
    },
  }
}

/** 从 /{locale}/xxx 形式的 pathname 提取 locale 之外的相对路径（如 /about） */
export function stripLocaleFromPath(pathname: string, locale: string): string {
  const segs = pathname.split('/').filter(Boolean)
  if (segs.length > 0 && segs[0] === locale) segs.shift()
  return segs.length ? `/${segs.join('/')}` : ''
}
