import type { CollectionConfig } from 'payload'

export const CaseStudies: CollectionConfig = {
  slug: 'caseStudies',
  labels: { singular: 'Case Study', plural: 'Case Studies' },
  admin: {
    useAsTitle: 'title',
    group: 'Content',
    description: 'Customer projects and farm installations. Featured studies appear on the homepage.',
    defaultColumns: ['title', 'country', 'featured', 'published', 'sortOrder', 'updatedAt'],
    listSearchableFields: ['title', 'summary', 'location', 'farmName'],
    pagination: { defaultLimit: 20, limits: [10, 20, 50] },
  },
  access: { read: () => true },
  fields: [
    { name: 'title', type: 'text', required: true, localized: true },
    { name: 'slug', type: 'text', required: true, unique: true },
    { name: 'subtitle', type: 'text', localized: true },
    { name: 'summary', type: 'textarea', localized: true, admin: { description: 'Short card summary.' } },
    { name: 'content', type: 'richText', localized: true },
    { name: 'location', type: 'text', localized: true },
    { name: 'equipment', type: 'textarea', localized: true, label: 'Equipment Supplied' },
    { name: 'application', type: 'textarea', localized: true, label: 'Application' },
    { name: 'challenge', type: 'textarea', localized: true, label: 'Project Challenge' },
    { name: 'country', type: 'relationship', relationTo: 'countries' },
    { name: 'solution', type: 'relationship', relationTo: 'solutions' },
    { name: 'farmName', type: 'text', localized: true },
    { name: 'farmScale', type: 'text', localized: true },
    { name: 'keyResult', type: 'text', localized: true, admin: { description: 'Headline result, e.g. “+30% egg production”.' } },
    { name: 'image', type: 'relationship', relationTo: 'media' },
    { name: 'featured', type: 'checkbox', defaultValue: false, admin: { position: 'sidebar' } },
    { name: 'published', type: 'checkbox', defaultValue: true, admin: { position: 'sidebar' } },
    { name: 'sortOrder', type: 'number', defaultValue: 0, admin: { position: 'sidebar', description: 'Lower numbers appear first.' } },
  ],
  timestamps: true,
}
