/**
 * Copies every row from the local SQLite development database into a Postgres
 * database, so a production database can be rebuilt from the local snapshot.
 *
 * WHY THIS EXISTS
 * ---------------
 * `scripts/sync-catalogue-to-prod.ts` populates production through the Payload
 * Local API. That is the right tool when production is alive and only some
 * content is missing, but it is the wrong tool for a full recovery:
 *
 *   - it re-uploads media through the Blob adapter, which duplicates every file
 *     in Vercel Blob (454 objects / 545 MB would become ~1.09 GB);
 *   - it is slow, because each document costs a round trip plus array handling;
 *   - it only covers the collections it knows about.
 *
 * A row-for-row copy avoids all three. It is safe because the Postgres schema is
 * generated by the same Payload config that generated the SQLite schema, so the
 * table and column sets match exactly (verified: 68 tables on both sides).
 *
 * HOW IT HANDLES FOREIGN KEYS
 * ---------------------------
 * The schema carries 89 foreign keys, and Neon's `neondb_owner` is not a
 * superuser, so `SET session_replication_role = replica` is denied (42501).
 * Instead the tables are inserted in topological order: a table is only written
 * after every table it references. There are no self-referencing foreign keys.
 *
 * WHAT IT SKIPS
 * -------------
 *   - `payload_migrations`: recording the local dev marker (`batch = -1`) is
 *     exactly the bug described in docs/MAINTENANCE.md §12.8, and copying it
 *     would make `vercel-build`'s `payload migrate` silently skip everything.
 *     Pass `--mark-migrations` to instead record the repo's migrations as
 *     applied (correct on a schema that was created by push).
 *   - `sqlite_*` internal tables.
 *
 * USAGE
 * -----
 *   POSTGRES_URL='postgresql://...' pnpm tsx scripts/copy-sqlite-to-postgres.ts --apply
 *   POSTGRES_URL='postgresql://...' pnpm tsx scripts/copy-sqlite-to-postgres.ts --apply --mark-migrations
 */
import 'dotenv/config'
import path from 'path'
import { createClient } from '@libsql/client'
import pg from 'pg'

const args = process.argv.slice(2)
const apply = args.includes('--apply')
const markMigrations = args.includes('--mark-migrations')
const ROOT = path.resolve(import.meta.dirname, '..')

const connectionString = process.env.POSTGRES_URL
if (!connectionString) {
  console.error('POSTGRES_URL is not set.')
  process.exit(1)
}

const lite = createClient({ url: `file:${path.join(ROOT, 'agricon-dev.db')}` })
const pgc = new pg.Client({ connectionString, ssl: { rejectUnauthorized: false }, connectionTimeoutMillis: 30_000 })
pgc.on('error', () => {})
await pgc.connect()
const q = async <T = any>(sql: string, values: unknown[] = []): Promise<T[]> => (await pgc.query(sql, values as never[])).rows as T[]

const SKIP = new Set(['payload_migrations'])
const BATCH = 150

// ---------------------------------------------------------------- metadata ---

type Col = { table_name: string; column_name: string; data_type: string; udt_name: string }

const cols = await q<Col>(
  `SELECT table_name, column_name, data_type, udt_name
     FROM information_schema.columns WHERE table_schema = 'public'`,
)
const colsByTable = new Map<string, Col[]>()
for (const c of cols) {
  if (!colsByTable.has(c.table_name)) colsByTable.set(c.table_name, [])
  colsByTable.get(c.table_name)!.push(c)
}

const fks = await q<{ child: string; parent: string }>(
  `SELECT tc.table_name AS child, ccu.table_name AS parent
     FROM information_schema.table_constraints tc
     JOIN information_schema.key_column_usage kcu
       ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema
     JOIN information_schema.constraint_column_usage ccu
       ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'`,
)

const localTables = (
  await lite.execute(`SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name`)
).rows.map((r) => String((r as unknown as { name: string }).name))

const copyable = localTables.filter((t) => !SKIP.has(t) && colsByTable.has(t))

// Topological sort: parents before children.
const deps = new Map<string, Set<string>>(copyable.map((t) => [t, new Set<string>()]))
for (const { child, parent } of fks) {
  if (child !== parent && deps.has(child) && deps.has(parent)) deps.get(child)!.add(parent)
}
const ordered: string[] = []
const state = new Map<string, 0 | 1 | 2>() // 1 = visiting, 2 = done
function visit(t: string, trail: string[]): void {
  const st = state.get(t)
  if (st === 2) return
  if (st === 1) {
    console.warn(`  ! circular foreign key ignored: ${[...trail, t].join(' -> ')}`)
    return
  }
  state.set(t, 1)
  for (const d of deps.get(t) ?? []) visit(d, [...trail, t])
  state.set(t, 2)
  ordered.push(t)
}
for (const t of copyable) visit(t, [])

// -------------------------------------------------------------- conversion ---

/** Turns a SQLite value into something `pg` can bind for the given Postgres type. */
function convert(v: unknown, col: Col): { value: unknown; cast: string } {
  if (v === null || v === undefined) return { value: null, cast: '' }
  const { data_type: dt, udt_name: udt } = col

  if (dt === 'boolean') return { value: v === 1 || v === true || v === '1' || v === 'true', cast: '' }
  if (dt === 'integer' || dt === 'bigint' || dt === 'smallint') return { value: Number(v), cast: '' }
  if (dt === 'numeric' || dt === 'real' || dt === 'double precision') return { value: Number(v), cast: '' }

  if (udt === 'jsonb' || udt === 'json') {
    const s = String(v)
    if (s === '') return { value: null, cast: '' }
    // SQLite keeps JSON as text; Postgres needs it cast on the way in.
    return { value: s, cast: `::${udt}` }
  }

  let s = String(v)
  if ((udt === 'timestamp' || udt === 'timestamptz') && / [+-]\d{2}:?\d{2}$/.test(s)) {
    // SQLite writes `2026-09-25 23:49:36.123 +00:00`; Postgres wants no space.
    s = s.replace(/ ([+-]\d{2}:?\d{2})$/, '$1')
  }
  return { value: s, cast: '' }
}

// ------------------------------------------------------------------- copy ---

type Count = { local: number; pg: number }
const report = new Map<string, Count>()
let insertedTotal = 0
const failures: string[] = []

console.log(apply ? 'APPLY — writing to Postgres\n' : 'DRY RUN — no writes (pass --apply)\n')

await pgc.query('BEGIN')
try {
  for (const table of ordered) {
    const tableCols = colsByTable.get(table)!
    const localRows = (await lite.execute(`SELECT * FROM "${table}"`)).rows as unknown as Array<Record<string, unknown>>
    const existing = Number((await q<{ n: string }>(`SELECT COUNT(*)::int AS n FROM "${table}"`))[0].n)
    report.set(table, { local: localRows.length, pg: existing })
    if (localRows.length === 0) continue

    if (existing > 0) {
      console.log(`  ${table.padEnd(46)} skip (already has ${existing} rows)`)
      continue
    }

    // Only columns present on both sides.
    const localColNames = new Set(Object.keys(localRows[0]))
    const use = tableCols.filter((c) => localColNames.has(c.column_name))
    const names = use.map((c) => `"${c.column_name}"`).join(', ')

    for (let start = 0; start < localRows.length; start += BATCH) {
      const chunk = localRows.slice(start, start + BATCH)
      const params: unknown[] = []
      const tuples: string[] = []
      for (const row of chunk) {
        const ph: string[] = []
        for (const c of use) {
          const { value, cast } = convert(row[c.column_name], c)
          params.push(value)
          ph.push(`$${params.length}${cast}`)
        }
        tuples.push(`(${ph.join(',')})`)
      }
      const sql = `INSERT INTO "${table}" (${names}) VALUES ${tuples.join(',')}`
      if (apply) await q(sql, params)
    }
    insertedTotal += localRows.length
    console.log(`  ${table.padEnd(46)} +${localRows.length}`)
  }

  // Sequences: rows were inserted with explicit ids, so the counters are stale.
  if (apply) {
    const seqTables = await q<{ table_name: string; column_name: string }>(
      `SELECT table_name, column_name FROM information_schema.columns
        WHERE table_schema='public' AND column_default LIKE 'nextval(%'`,
    )
    let fixed = 0
    for (const { table_name, column_name } of seqTables) {
      const r = await q<{ max: string | null }>(`SELECT MAX("${column_name}")::text AS max FROM "${table_name}"`)
      if (r[0]?.max === null || r[0]?.max === undefined) continue
      await q(`SELECT setval(pg_get_serial_sequence($1, $2), $3, true)`, [table_name, column_name, Number(r[0].max)])
      fixed++
    }
    console.log(`\nsequences reset: ${fixed}`)
  }

  if (apply && markMigrations) {
    // Read the names off disk rather than importing the module: the schema was
    // built by push, so both migrations are already fully reflected and must be
    // recorded as applied. Leaving them pending is not harmless — the first one
    // runs `ALTER TABLE ... ALTER COLUMN "quote" DROP NOT NULL` on legacy columns
    // that a freshly pushed schema does not have, so `payload migrate` in
    // `vercel-build` would fail and take the whole deployment with it.
    const { readdirSync } = await import('fs')
    const names = readdirSync(path.join(ROOT, 'src', 'migrations'))
      .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
      .map((f) => f.replace(/\.ts$/, ''))
      .sort()
    let batch = 1
    for (const name of names) {
      await q(`INSERT INTO payload_migrations (name, batch) VALUES ($1, $2)`, [name, batch])
      console.log(`  recorded migration: ${name} (batch ${batch})`)
      batch++
    }
  }

  if (apply) await pgc.query('COMMIT')
  else await pgc.query('ROLLBACK')
} catch (err) {
  await pgc.query('ROLLBACK')
  console.error('\nFAILED, rolled back:', err instanceof Error ? err.message : err)
  failures.push(String(err))
}

// -------------------------------------------------------------- verify ------

console.log('\n=== verification (local vs postgres) ===')
let mismatches = 0
for (const [table, { local, pg: before }] of report) {
  const after = Number((await q<{ n: string }>(`SELECT COUNT(*)::int AS n FROM "${table}"`))[0].n)
  const ok = after === local
  if (!ok) mismatches++
  if (local > 0 || after > 0) {
    console.log(`  ${ok ? 'ok  ' : 'DIFF'} ${table.padEnd(46)} local=${local} pg=${after}${before > 0 ? ` (was ${before})` : ''}`)
  }
}
console.log(`\nrows written: ${insertedTotal}; tables compared: ${report.size}; mismatches: ${mismatches}`)
if (failures.length) console.log('failures:', failures.join(' | '))

await lite.close()
await pgc.end()
process.exit(mismatches === 0 && failures.length === 0 ? 0 : 1)
